### ISSUE TITLE
请教一下，map 如何嵌套 自定义的bean

### ISSUE THREAD

**Issue by cchorseless** [focus-creative-games/luban_examples#16]
\# #		id--------|---------------------- *test---------------------------|
\##type	string	|---------- map,string,XXBean---------------------------|
\##var	--------|----------|bean_prop_a	 | bean_prop_b  |	bean_prop_c |
\# #		表的key	| map的key |	bean字段a     | bean字段b    |    bean字段c  |

map嵌套的bean 如何使用var 限定字段

**Comment by pirunxi** [comment]
目前不支持。你可以使用list,Bean替代。list支持index特性，可以额外生成一个索引的map，这样使用起来跟你期望的基本一致。 用法 type="(list#index=xxxKey),Xxbean
