### ISSUE TITLE
GDScript

### ISSUE THREAD

**Issue by luochen7452** [focus-creative-games/luban_examples#20]
func get(key):
loader.call(
这两个现在在godot4下都会报错

mac下临时用替换处理了
sed -i "" "s/get(/get_tb(/g" ${WORKSPACE}/auto_gen/config_data/types.gd
sed -i "" "s/loader.call(/loader.load(/g" ${WORKSPACE}/auto_gen/config_data/types.gd

**Comment by pirunxi** [comment]
感谢哈，这个我们找时间修复一下
