### ISSUE TITLE
请问一下list表的index怎么混用多键联合索引与多键独立索引？

### ISSUE THREAD

**Issue by DevinTsing** [focus-creative-games/luban_examples#22]
你好，我现在在做一个装备表，里面有这个需求，就是同一件装备有不同的等级，每个不同的等级都是独立的数据，也有独立的id。现在我想既能通过id获取这件装备数据，也想通过这件装备的名称+等级的形式获取对应的装备数据，所以想将联合索引和独立索引同时使用。现在我试了一下，好像通过,与+行不通。请问现在能实现这种么？

**Comment by pirunxi** [comment]
这个小众特殊需求，加载后自己索引就行了。
