### ISSUE TITLE
填表格式上的问题

### ISSUE THREAD

**Issue by kilora** [focus-creative-games/luban_examples#38]
我类型编辑成这样(list#sep=|),(int#ref=ID@card.TbUnitPart)不可以吗？（报错了）
希望能一个用一个单元格填上UnitPart表的ID，并自检；
1001|1002|1003
1003|1002
1003|1002
不自检就不会报错，但填这些数据，没自检感觉不行

**Comment by pirunxi** [comment]
这是可以的，详细可以见数据校验相关文档。如果有问题去群里讨论，可以提供一个复现例子给我们。但这些功能是久经考验的，有问题的概率很低。
